services:
  aprenant_db:
    container_name: aprenant_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin0000
      MYSQL_DATABASE: aprenant_db
    ports:
      - "3306:3306"
    networks:
      - enaa-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_db:
    container_name: auth_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin0000
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    networks:
      - enaa-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  brief_db:
    container_name: brief_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin0000
      MYSQL_DATABASE: brief_db
    ports:
      - "3308:3306"
    networks:
      - enaa-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rendu_db:
    container_name: rendu_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin0000
      MYSQL_DATABASE: rendu_db
    ports:
      - "3309:3306"
    networks:
      - enaa-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka:
    container_name: eureka-service
    build:
      context: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - enaa-net
    environment:
      SPRING_APPLICATION_NAME: eureka-service
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  api-gateway:
    container_name: apiGateway-service
    build:
      context: ./apiGateway-service
    ports:
      - "8085:8085"
    depends_on:
      eureka:
        condition: service_started
    networks:
      - enaa-net
    environment:
      SPRING_APPLICATION_NAME: apiGateway-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: auth-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:8080
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/auth/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: Brief-Service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://Brief-Service:8080
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/brief/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: Rendu-Service
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://Rendu-service:8080
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/rendu/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0: StripPrefix=1
      SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0: AddResponseHeader=X-Gateway,ENAA API Gateway
      SPRING_MAIN_WEB_APPLICATION_TYPE: reactive

  brief-service:
    container_name: brief-service
    build:
      context: ./brief-service
    ports:
      - "8081:8080"
    depends_on:
      brief_db:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://brief_db:3306/brief_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin0000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  aprenant-service:
    container_name: aprenant-service
    build:
      context: ./aprenant-service
    ports:
      - "8082:8080"
    depends_on:
      aprenant_db:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://aprenant_db:3306/aprenant_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin0000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
    ports:
      - "8084:8080"
    depends_on:
      auth_db:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth_db:3306/auth_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin0000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  rendu-service:
    container_name: rendu-service
    build:
      context: ./rendu-service
    ports:
      - "8083:8080"
    depends_on:
      rendu_db:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://rendu_db:3306/rendu_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin0000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

networks:
  enaa-net: